# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: try-github-actions
on:
  workflow_dispatch:
    inputs:
      env_name:
        description: ' Environment to test(dev3, qa) '
        required: true
        default: 'dev3'
      
jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/strongarm-tech/satbuildmachine:latest
    #   credentials:
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITTOKEN }}
          
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install -U urllib3 requests
        pip install --user --upgrade selenium
        pip install behave
        pip install selenium
        pip install chromedriver
        pip install webdriver-manager

    - name: run behave file
      env:
        EMAIL_DB : ${{ secrets.EMAIL_DB }}
        PASS_DB : ${{ secrets.PASS_DB }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      run: |
            cd Tests
            case ${{ github.event.inputs.env_name }} in  
            dev3)
            behave -i dev3.feature
            ;;
            qa)
            behave -i qa.feature
            ;;
            esac



    
