# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: try-github-actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      env_name:
        description: ' Environment to test(dev3, qa) '
        required: true
        default: 'dev3'
      
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
        pip install case
        pip install behave
        pip install selenium
        pip install chromedriver
        pip install webdriver-manager
    - name: run behave file
      env:
        EMAIL_DB : ${{ secrets.EMAIL_DB }}
        PASS_DB : ${{ secrets.PASS_DB }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      # run: |
      #       if ( {{github.event.inputs.env_name}} == "dev3" ) { cd Tests/behave features\dev3.feature }
      #       else:
      #         cd Tests/behave features\qa.feature

      run: |
            case ${{ github.event.inputs.env_name }} in  
            dev3)
            echo cd Tests
            echo behave features\dev3.feature
            ;;
            qa)
            echo cd Tests
            echo behave features\qa.feature
            ;;
            esac
      # if: ${{ github.event.inputs.env_name }} == "dev3"
      #     cd Tests/behave features\dev3.feature
      # elif: ${{ github.event.inputs.env_name }} ==

